### ISSUE TITLE
Data rate in examples is overwritten by library

### ISSUE THREAD

**Issue by Freefly18** [sparkfun/SparkFun_BNO080_Arduino_Library#10]
Take for example, Example1-RotationVector.ino:

```
  Wire.begin();
  Wire.setClock(400000); //Increase I2C data rate to 400kHz
  myIMU.begin();
```

In SparkFun_BNO080_Arduino_Library.cpp:

```
boolean BNO080::begin(uint8_t deviceAddress, TwoWire &wirePort)
{
  _deviceAddress = deviceAddress; //If provided, store the I2C address from user
  _i2cPort = &wirePort; //Grab which port the user wants us to use

  //We expect caller to begin their I2C port, with the speed of their choice external to the library
  //But if they forget, we start the hardware here.
  _i2cPort->begin();

  [...]
}
```

Wire.begin() resets the I2C interface, including the clock rate. In my case the default was 100kHz.

**Comment by nseidle** [comment]
This is a really good point that I had not thought of. Thanks! We enjoy the 'safety' of having a 

    _i2cPort->begin();

inside the library but we'll have to move the setClock() in the examples beyond the myIMU.begin().

**Comment by nseidle** [comment]
Examples have been modified in latest lib version.
