### ISSUE TITLE
Uncertain on sensor rates

### ISSUE THREAD

**Issue by adamoskaranikas** [sparkfun/SparkFun_BNO080_Arduino_Library#101]
### Subject of the issue
Using SPI, I've come across a  bit of strange behaviour that i'm not sure if its due to my system implementation or a limitation from the bno080. I'm running SPI at 3MHz. I can enable a single sensor and get pretty much the max reported rate (which im very happy with), but once I enable more than one sensor I can't really get anywhere near the maximum rates without losing stability. 

### Your workbench
* What development board or microcontroller are you using?
ESP32
* What version of hardware or breakout board are you using? 
BNO080 Sparkfun breakout 
* How is the breakout board to your microcontroller?
 SPI
* How is everything being powered?
USB
* Are there any additional details that may help us help you?
Running on esp-idf framework but sensor is only interacted through this driver which is connected to esp32-arduino core.
### Steps to reproduce
At the moment I'll leave a reproducible example out, as I have a feeling its just that each sensor has its own list of discrete rates it actually can operate at, and when I'm requesting some rate outside of that list it messes with the other sensors. I'm wondering if you guys have this information available or if I just need to trial and error it.  I'm using the sequence number from the shtpHeader to count and compare the messages in a set period of time to how many times my interrupt actually gets triggered per sensor.

### Expected behavior
I should get close to the requested rate for each sensor I enable, or at least it should report according to the datasheet (0.9*rate < rate < 2.1*rate). 

### Actual behavior
When running at 100Hz, everything is still good. with gyro, accelerometer, and rotation vector reporting near 100 Hz. When trying 200 Hz, the quaternion and gyroscope report around 200, but the accelerometer only gets up to 125 Hz at the best of times, which after some testing i found is part of its discrete list (125, 250, 500). But on bad runs it can get as low as 5.5 Hz. In general it feels like there's a limit on the BNO when more than one sensor is reporting like i only have X Hz to play with and must split it between the sensors in order to not get funky behaviour. 

Part of the rate drop is due to messages being dropped, as sometimes my sequence count for a sensor does not increase monotonically but skips numbers. I hope that this is an issue on my side (taking too long to deal with a message before the next comes in?) and not that the BNO080 has some limit to operating multiple sensors. In terms of bandwidth I believe that i'm still well below the 3MHz clock limit. 

Any ideas/knowledge here would be awesome. If this is actually something up with the sensor let me know and I can provide an example code to show the performance. 

Thanks

**Comment by PaulZC** [comment]
Hi @adamoskaranikas ,

For questions like this, you might receive more replies if you post it in the IMU Forum:
https://forum.sparkfun.com/viewforum.php?f=83

This does not appear to be an issue with the library, more a quirk of how the BNO080 operates, but I'm happy to leave it open for a while just in case anyone can help.

Best wishes,
Paul

**Comment by adamoskaranikas** [comment]
Hi @PaulZC ,

Glad to know it's not a problem on the library side, I posted a question on the forum as you suggested. I'll close the issue in a couple days just in case someone here has any idea as you say, hopefully with some good news from the forum.

Thanks for the quick reply :)
