### ISSUE TITLE
[Feature Request] Add functionality to access Gravity packets

### ISSUE THREAD

**Issue by anant3110** [sparkfun/SparkFun_BNO080_Arduino_Library#103]
### Subject of the issue
The IMU allows to access gravity packets, but the library doesn't. 

### Expected behavior
Have a setGravityReport() function to set gravity packets. Have a getGravityX(), getGravityY() and getGravityZ() to get the relevant variables once they have been updated.

**Comment by PaulZC** [comment]
Closed by #104
