### ISSUE TITLE
Cannot upload arduino sketch on IMU(BNO080) through CH340G

### ISSUE THREAD

**Issue by sauvikchdhry** [sparkfun/SparkFun_BNO080_Arduino_Library#2]
With all the connections made and drivers installed, I am failing to upload arduino sketch on BNO080. 
In "**Arduino.exe > Tools >** 
                                      _**Board:**  the default selected is 'Arduino/Genuino Uno'.
                                      **Port**: The detected one (COM9 in my case)_
And then I try uploading. But fails to upload.

**_Note:_** CH340G tested and is working fine. (Tx/Rx loop back test)..Possible guess is that it cannot recognize the board selected. Any help is appreciated. Thanks!!

**Comment by nseidle** [comment]
Hi s05vik,

Perhaps there is some confusion. You cannot upload sketches to the BNO080 board. This library and the examples are designed to be uploaded to a RedBoard or Arduino Uno.

The BNO080 has a serial interface but is uses a different format that this library is not compatible with.

Cheers,
-Nathan

**Comment by sauvikchdhry** [comment]
@nseidle  Perhaps the confusion lies in this link which suggests otherwise or better if there is any way to communicate with the IMU found at : _https://www.sparkfun.com/products/14618_
And It suggests the user to use the library found at:
_https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library_

Any hint will really be appreciated!!

**Comment by nseidle** [comment]
Hi,

I am very sorry and do not want to mislead any customer. If you have a unit and want to return a product we are happy to give you a refund. Just let me know.

To answer your concern, I still don't see the text on the product page or the library page that would lead a customer to believe that this product is programmable with an Arduino sketch. 

The IMU080 is a sensor that is communicated with over various protocols including I2C, SPI, and serial. It has a serial interface. But that does not mean it can be programmed with Arduino.

Again, I'm really sorry about any confusion. Please help me write a better product description and I will change it.

Cheers,
-Nathan
