### ISSUE TITLE
NULL compilation warning

### ISSUE THREAD

**Issue by MichaelPriven** [sparkfun/SparkFun_BNO080_Arduino_Library#25]
Hi,

I suggest to change ...**uint8_t intPin = NULL** to uint8_t intPin = 255 to avoid compilation warning / error (in new version of Arduino IDE)

Thanks
Michael

**Comment by nseidle** [comment]
Thanks! What microcontroller are you using? What version of the IDE are you using? I can't replicate on Uno or Artemis in Arduino v1.8.9.

**Comment by MichaelPriven** [comment]
I'm using Arduino Mega, with V1.8.9 or visual studio with visual micro

**Comment by nseidle** [comment]
Oddly I can't replicate. Windows 10, Arduino v1.8.9. Have you modified your platforms.txt? It sounds like the warnings on Arduino have been tweaked up in your version.

Regardless, I've changed the problem line of code and should roll with then next lib version.

Thanks for reporting!
