### ISSUE TITLE
 Question frame of reference 

### ISSUE THREAD

**Issue by A-Shot** [sparkfun/SparkFun_BNO080_Arduino_Library#26]
How to change the frame of reference?

**Comment by nseidle** [comment]
Unless you're reading about a feature in the datasheet that I'm not, you can't. Checkout the BNO080 datasheet section 4 'BNO080 Orientation' for more info.

**Comment by jerabaul29** [comment]
This may be related to #65 . You can use the quaternion output to change the data into a East-North-Up frame of reference.
