### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_BNO080_Arduino_Library#3]
The function "waitForI2C()" can be removed, since there is no need to wait for something after a Wire.requestFrom().

When the Wire library was able to detect a I2C bus error, the number of received bytes could be zero. That can be used to detect an error.

For example:
```
_i2cPort->requestFrom(_deviceAddress, 4);
if(_i2cPort->available() != 4) return (false); //Error
```

**Comment by nseidle** [comment]
Thanks Koepel. What lines are you referring to?

A PR is most helpful.

**Comment by Koepel** [comment]
In the file "SparkFun_BNO080_Arduino_Library.cpp" the function requestFrom() is used twice. There is not need to wait for something after calling requestFrom(). The complete function "waitForI2C()" can be removed.

Since the return value of the endTransmission() is checked for an error, it might be good to also do a check after the requestFrom().

For example these lines:
 ```
 _i2cPort->requestFrom((uint8_t)_deviceAddress, (uint8_t)4); //Ask for four bytes to find out how much data we need to read
  if (waitForI2C() == false) return (false); //Error
```

can be changed to:
```
_i2cPort->requestFrom(_deviceAddress, 4); //Ask for four bytes to find out how much data we need to read
if(_i2cPort->available() != 4) return (false); //Error
```

And the same for the other requestFrom().

**Comment by nseidle** [comment]
Hi Koepel, While I agree you are technically correct, after testing your recommendations my library stops working. This is why a PR is ideal. 

Since this is not a 'library-is-broken' issue I'm going to close it. But please don't take it as disrespectful. I do appreciate you pushing me to write better code.

**Comment by Koepel** [comment]
That means I will be spending a lot of time in forums, trying to explain not to use the Wire library like that, because this code will be copied and used as an example.

I don't know why it stopped. The extra unnecessary code creates a small delay, but removing that can not be the problem. I don't have a BNO080, but tell me if need to check code.

**Comment by Koepel** [comment]
pwesson found the same problem with the BNO080. It stops working when the extra code is removed: https://github.com/pwesson/roboticboat/issues/3
