### ISSUE TITLE
Example8-ActivityClassifier.ino not working

### ISSUE THREAD

**Issue by akod1ng** [sparkfun/SparkFun_BNO080_Arduino_Library#33]
### Subject of the issue
The example for the ActivityClassifier.ino seems to be broken.
It seems that 'printActivityName' was not declared. 

Error in Arduino IDE: `'printActivityName' was not declared in this scope`

I tried to define it but get `'printActivityName' cannot be used as a function`.

Any tips?

### Steps to reproduce
Open Example8-ActivityClassifier.ino and verify it in Arduino IDE. 

### Expected behavior
Ino should compile

### Actual behavior
Fails with error: printActivityName' was not declared in this scope

**Comment by nseidle** [comment]
Works fine for me. I can't help you much if you don't tell us how to reproduce the issue but you've deleted the part of the issue report that is rather important... Please reopen once you've filled out a full report.

### Your workbench
* What development board or microcontroller are you using?
* What version of hardware or breakout board are you using? 
* How is the breakout board to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?
