### ISSUE TITLE
SPI examples not working

### ISSUE THREAD

**Issue by leaf0810** [sparkfun/SparkFun_BNO080_Arduino_Library#35]
### Something wrong with function myIMU.beginSPI()
I run SPI examples with arduino uno and BNO080 imu.But I failed.I'm sure the connection is right.However,I got the warning,"BNO080 over SPI not detected. Are you sure you have all 6 connections? Freezing..."
And I test  the interface ,!INT,no valtage. Is there something wrong with IMU?

### Your workbench
Arduino uno;  Sparkfun BNO080 IMU.

### Steps to reproduce
Open Example1-RotationVector.ino and run it in Arduino IDE.

### Expected behavior
no "BNO080 over SPI not detected. Are you sure you have all 6 connections? Freezing..."

### Actual behavior
here it print:
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI Wait
SPI INT timeout
BNO080 over SPI not detected. Are you sure you have all 6 connections? Freezing...

**Comment by nseidle** [comment]
I just retested the SPI interface. Everything is working fine. Be sure to check the instructions on the example again. For SPI to work:

* Close PS1
* Clear the I2C pull up jumper
* Make sure PS0 is open

I'm going to close this issue but if you continue to have problems please let us know.
