### ISSUE TITLE
How to set or write FRS record and How to set system orientation 

### ISSUE THREAD

**Issue by ManeeshSingh1920** [sparkfun/SparkFun_BNO080_Arduino_Library#52]
### Subject of the issue
How to set or write FRS record and How to set system orientation 

### Your workbench
I am using Arduino Uno and to test the Sparkfun BNO080 module and the latest Sparkfun library. 

### Steps to reproduce
I want to do calibration for system orientation as given in BNO080 Datasheet Page number 40 - 42 
i.e. BNO080 Orientation But I didn't find any way to do that in this library. 

How can I do system orientation and tare function orientation from this library?

**Comment by PaulZC** [comment]
Hello @ManeeshSingh1920 ,
If you need advice about how to use the BNO080 module, please use the forum:
https://forum.sparkfun.com/viewforum.php?f=83&sid=a248a524f6e9d096962c2f6b8b4f46b0
Please only use GitHub Issues to report _faults_ in the code.
Best wishes,
Paul
