### ISSUE TITLE
Returning Gravity Vector?

### ISSUE THREAD

**Issue by myleskeller** [sparkfun/SparkFun_BNO080_Arduino_Library#54]
This is more of a confirmation of my attempted solution than an issue. I would like to retrieve the actual vector associated with the force of gravity. Since linear acceleration returns acceleration sans the force of gravity, am I to assume that gravity could be calculated using the following?

`<gravity> =  <acceleration> - <linearAcceleration>`

**Comment by PaulZC** [comment]
Hi @myleskeller ,
I'm not sure if I completely understand your question.
You can read the three accelerometer readings and, yes, you will see a reading of 1g on one of the axes, if that axis is pointing straight up/down. If the sensor is tilted, the 1g will be distributed among the three axes.
The other way to think about it is in terms of the Euler angles. If you read the roll and pitch, you can use them to calculate a vector which points down.
I'm going to close this issue as this is not an issue with the library. The IMU forum is the best place to ask for advice if you need more help:
https://forum.sparkfun.com/viewforum.php?f=83
Best wishes,
Paul
