### ISSUE TITLE
Adding examples including getReading and multiple access

### ISSUE THREAD

**Issue by guihomework** [sparkfun/SparkFun_BNO080_Arduino_Library#58]
I open this issue here related to a future PR I prepare with an example for the getReadings #55 combined with the multiple access #56,  maybe even with an interrupt if I manage.

This avoids spamming a merged PR

**Comment by guihomework** [comment]
Dear @PaulZC ,

 You asked to try make the example generic to run on an arduino uno. Unfortunately I don't have the qwiic shield, I am using another breakout board with a BNO08x that does not have level-shifters. I was running fully on 3.3V, so out of the box I cannot try on an Arduino uno. I will at least prepare for teensy now and see later if I have time to add basic voltage dividers for outputs of the arduino (I read arduino will understand the 3.3V signals as a logical 1).

**Comment by guihomework** [comment]
Took me some time to debug why I had no interrupt coming, The fact was the interrupt had occurred before I had interrupts enabled, putting the BNO08x in a "data available" state and not producing a falling edge anymore. Enabling interrupts sooner solved the issue.

PR provided #59

**Comment by guihomework** [comment]
Dear @PaulZC , I don't need this example of this #59 to me merged in the release-candidate, but would like to know if you had time to look and test the release candidate so that it can be merged in master at some point.
I have been preparing some firmware with the release candidate and ported all my old code to the new "getReadings" method, and all works best so if it was in master, I would be thankful.

best
Guillaume

**Comment by PaulZC** [comment]
Hi Guillaume (@guihomework ),
Apologies - updating the BNO080 library has been on my "things to do" list for some time! Other projects got in the way...
I am making some small improvements to the library now, and hope to make a new release in a day or two.
Thank you again for all your support.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi Guillaume (@guihomework ),
Thank you again for all your contributions. v1.1.9 has just been released.
Closing...
Best wishes,
Paul

**Comment by guihomework** [comment]
@PaulZC wonderful, this release and new features are a great help for my developments. thanks
