### ISSUE TITLE
No Data from i2c on Nano or Uno

### ISSUE THREAD

**Issue by glyndavidson** [sparkfun/SparkFun_BNO080_Arduino_Library#61]
I'm getting the same results on both Arduino Nano & Uno - No data from the device.

"if (myIMU.begin())" returns false.

If I enable debugging (myIMU.enableDebugging(Serial)) I get "I2C Timeout".
```
BNO080 Read Example
Accelerometer enabled
Output in form x, y, z, in m/s^2
I2C timeout
I2C timeout
I2C timeout
```

Tried both of these but neither worked:
```
#define I2C_BUFFER_LENGTH BUFFER_LENGTH
#define I2C_BUFFER_LENGTH 32
```

Using i2c on a breadboard (Not Qwiic). 
Pins connected are:
3v3 -> 3v3
GND -> GND
SDA -> SDA
SCL -> SCL

Also tried with an external 3.3v power supply.

Power light on the breakout is on.

Using the default i2c address. Jumpers on the breakout are untouched (default i2c address).

Arduino IDE Version 1.8.12

Any suggestions please? Am I missing something really obvious?

**Comment by PaulZC** [comment]
Hi @glyndavidson ,
Are you using a SparkFun breakout?
(Could it be this issue? https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library/issues/51 )
Best wishes,
Paul

**Comment by glyndavidson** [comment]
Hi Paul 

Thanks for getting back to me. 

Yes, I'm using the sparkfun breakout.

Already tried changing the i2c address but that didn't work.

**Comment by PaulZC** [comment]
Hi @glyndavidson ,
My next guess is that it is a voltage level problem.
Are both your Arduino Nano and Uno 5V boards?
If they are, they are probably trying to pull SDA and SCL up to 5V, which could produce weird results.
You might find [one of these](https://www.sparkfun.com/products/15439) useful?
Best wishes,
Paul

**Comment by glyndavidson** [comment]
I've got an ATMega1284 running on a breadboard at 3.6v. I'll try it with that and see what happens.

**Comment by PaulZC** [comment]
Closing... Please re-open if this is still an issue.
