### ISSUE TITLE
Getting linear acceleration data 

### ISSUE THREAD

**Issue by ayu135** [sparkfun/SparkFun_BNO080_Arduino_Library#7]
Hi,
I was working with the bno080 sensor and wanted to get the linear acceleration data ie. the gravity subtracted acceleration but I wasn't able to use to getLinAccelX() function to get that data after calling the enableLinearAccelerometer() function. The arduino IDE doesn't even recognize the getLinAccel function and throws an error. 

After toiling around a bit i was able to get the data by modifying the report id for the normal accelerometer data to 0x04 in the macros in the header file of the library. I was hoping that instead of this work around we could use the normal linear acceleration functions to access that data.

**Comment by SHANTANUB009** [comment]
So, it was basically a swap between Raw acceleration GetAccelX _REPORT_ID(0x01) in the macros with Linear Acceleration getLinAccelX_REPORT_ID (0x04) in the SparkFun_BNO080_Arduino_Library.h file and then the getAccelX will itself give linear acceleratio in the arduino Example 2 _ Accelerometer.ino


This is wat is done 👍 

#define SENSOR_REPORTID_ACCELEROMETER 0x04 // original file has 0x01 ID

**Comment by nseidle** [comment]
I just pushed example 12 which shows how to use linear accel. Works for me. Let me know if you have any problems.

**Comment by SHANTANUB009** [comment]
Hey, Works great for me. Also compared the hack that i tried, with your new push, both give identical results.   And Thanks for the SPI interface as well.

**Comment by nseidle** [comment]
Very good! Happy to help.
