### ISSUE TITLE
what to do when already some data in buffer?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/SparkFun_BNO080_Arduino_Library#84]
I am trying to understand a bit more about the low level interfacing to the sensor.

It looks like there may be some problems now and then with some unexpected data in the I2C buffer, if I understand right:

https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library/blob/223cd8ee1850f5d36b80f3315937b96dfb188a3d/src/SparkFun_BNO080_Arduino_Library.cpp#L1471-L1477

I was curious of one thing: if there is some unexpected / corrupted data present, should it also be wiped out there? If not, can you explain why? :) .

**Comment by PaulZC** [comment]
Hi JR (@jerabaul29 ),
I added those lines when I was trying to debug the communication issues when using the Apollo3 (Artemis) boards. I found that asking the processor to do 'something else' before attempting to read the packet improved the reliability of the I2C communication. I'm not actually expecting there to be data in the buffer, I'm just using the ```available``` as the 'something else'. If you were to see that debug message, it would mean something very bad had happened...
Best wishes,
Paul
