### ISSUE TITLE
BNO085 Jump Detection - which report to choose?

### ISSUE THREAD

**Issue by marcel-bluestone** [sparkfun/SparkFun_BNO080_Arduino_Library#86]
Hello,

I want to use a BNO085 for jump detection. I thought this would be easy to see the # of jumps using the stepCounter report, but obviously if the step counter is not fast enough and regularly misses jumps. I tried the shake detector instead, but this also is far from reliable.

I have to say, that during the jumps the Y-Axis point upwards, but anyway the direction of the sensor did not make a difference in terms of reliability of counting each jump.

Does anyone have an idea, if there might be a better, robust solution?

Thanks

**Comment by PaulZC** [comment]
Hi @marcel-bluestone ,
It is best to ask general questions like this in the [Inertial Measurement Unit forum](https://forum.sparkfun.com/viewforum.php?f=83).
Best wishes,
Paul
