### ISSUE TITLE
Gyro and accelerometer readings are repeating often

### ISSUE THREAD

**Issue by SHANTANUB009** [sparkfun/SparkFun_BNO080_Arduino_Library#9]
Hello, 
I am using quat, accel, gyro reading for pose estimation, the update time is this : 
myIMU.enableRotationVector(50); 
myIMU.enableAccelerometer(50);
myIMU.enableGyro(50);

Baurate(115200)

No delay command!

when i am viewing data in serial monitor, i am finding that some gyro n accelerometer data is repeating. I  feel there is an issue wit the enable command( i.e the time between reports). (It might be this way, i am moving the sensor slower than the sensor update time). 

Dear @nseidle let me know if you can help me out. 

Thanks.

**Comment by Freefly18** [comment]
@SHANTANUB009 Without a delay, you are simply requesting continuously the latest data from the IMU. The update time is the time between each, well, update of the data on the sensor itself.

If you want to pull the data in sync with the updates, you will have to look into Interrupts and modify the library. The BNO080 sets a pin to LOW when it does an update: use this to trigger an interrupt on your Arduino, which will read the data.

**Comment by nseidle** [comment]
@Freefly18 - Awesome! Thanks for helping with issues.

@SHANTANUB009 - I agree with Freefly18. If you need to re-open the issue, please do so.
