### ISSUE TITLE
SPI examples have incorrect comments

### ISSUE THREAD

**Issue by EmDash00** [sparkfun/SparkFun_BNO080_Arduino_Library#91]
On the SPI examples it states that the PS1 jumper must be closed and the PS0 jumper must be open; however, this is incorrect. 

According to the wiring guide for the jumpers, both PS1 and PS0 must be closed for SPI.
https://learn.sparkfun.com/tutorials/qwiic-vr-imu-bno080-hookup-guide

**Comment by PaulZC** [comment]
Hi Drason (@EmDash00 ),

Both the code examples and the hook-up guide are correct. Let me explain why.

The BNO080 needs both PS0 and PS1 to be pulled high at reset to place the chip in SPI mode.
On our breakout, the PS pins are normally pulled low by resistors. Closing the jumpers pulls them high.
But, the PS0 pin is also used for the WAKE signal in SPI mode. If you close the PS0 jumper, you cannot use the WAKE signal.
So, instead, we have the library pull the PS0 pin high during reset to put the chip in SPI mode:
https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library/blob/f318297613a7dbde485c1b4fb20fe7d39cc22a71/src/SparkFun_BNO080_Arduino_Library.cpp#L103-L110

Best wishes,
Paul
