### ISSUE TITLE
Sensors raw data conversion

### ISSUE THREAD

**Issue by zoharshemesh** [sparkfun/SparkFun_BNO080_Arduino_Library#97]
### Subject of the issue
Hello, 
I need to use the physical sensors reading (e.g. raw data). I can not find anywhere the sensors scaling conversion from ADC/LSB to the physical real value.

Do you know how to convert the raw data values to physical real values (I do not want to use the sensor's already calibrated data).

Thanks,
Zohar Shemesh

**Comment by PaulZC** [comment]
Hi @zoharshemesh ,

If the scaling is not defined in the documentation, then I'm afraid we cannot help you.

https://github.com/sparkfun/Qwiic_IMU_BNO080/tree/master/Documents

Best wishes,
Paul
